### ISSUE TITLE
Meteor/Node version related issue I believe

### ISSUE THREAD

**Issue by davidsyoung** [apollostack/apollo-server#54]
Hi, I'm having an issue when I import apollo-server into my meteor project. 

Below is the error: 

`/Users/davidyoung/Dev/gobeyond/.meteor/local/build/programs/server/packages/modules.js:41096
const graphql = require('graphql');
^^^^^     
SyntaxError: Use of const in strict mode.
at /Users/davidyoung/Dev/gobeyond/.meteor/local/build/programs/server/boot.js:292:30
at Array.forEach (native)
at Function._.each._.forEach (/Users/davidyoung/.meteor/packages/meteor-tool/.1.3.5_1.1fnktti++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
at /Users/davidyoung/Dev/gobeyond/.meteor/local/build/programs/server/boot.js:133:5`

Any way of sorting this?

**Comment by davidsyoung** [comment]
I can confirm that this error doesn't happen in `apollo-server@0.1.5`, and just in the new `apollo-server@0.2.0-rc.1` version.

How to reproduce in meteor-starter-kit:

`meteor npm remove apollo-server
meteor npm install apollo-server@0.2.0-rc.1 --save
meteor run`

**Comment by vangorra** [comment]
:+1:

**Comment by tymoor** [comment]
I'm getting an error running:
   `npm install apollo-server --save`
... which fails trying to install apollo-server@0.2.0-rc.1 into an existing meteor app.

Error says:
   `Failed at the apollo-server@0.2.0-rc.1 postinstall script 'typings install && npm dedupe'.`

Using @0.1.5 works.

**Comment by davidsyoung** [comment]
You need to do npm install -g typing a I found.

**Comment by smeijer** [comment]
Thanks @davidsyoung, `npm install -g typings` was indeed the way to solve this.

Looks like an error in the package.json. Depending on globally available modules is a bad thing.

**Comment by juanpaco** [comment]
Alternatively, if you `npm install  --save-dev typings` you don't have to install it globally.

**Comment by helfer** [comment]
This should be fixed now, I believe.

**Comment by do-n-khanh** [comment]
I am using "apollo-server": "^0.2.1", and Meteor 1.4. And I still get this problem.

**Comment by hlandao** [comment]
@helfer it seems that the issue still occurring using "0.2.3"

**Comment by helfer** [comment]
@do-n-khanh @hlandao What's the exact error you guys are getting?

**Comment by do-n-khanh** [comment]
@helfer : Thanks. I am getting the error #54 (SyntaxError: Use of const in strict mode. at ...)
---------------

/Users/davidyoung/Dev/gobeyond/.meteor/local/build/programs/server/packages/modules.js:41096 const graphql = require('graphql'); ^^^^^ SyntaxError: Use of const in strict mode. at /Users/davidyoung/Dev/gobeyond/.meteor/local/build/programs/server/boot.js:292:30 at Array.forEach (native) at Function._.each._.forEach (/Users/davidyoung/.meteor/packages/meteor-tool/.1.3.5_1.1fnktti++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11) at /Users/davidyoung/Dev/gobeyond/.meteor/local/build/programs/server/boot.js:133:5

**Comment by helfer** [comment]
@do-n-khanh This seems to be related to the meteor-integration package which I assume you're using, so it would be better to open an issue there, because you'll be more likely to get help that way.

**Comment by helfer** [comment]
Closing this since it's more pertinent to meteor-integration than apollo-server.
